version: '1'
services:
  flask:
    build: .
    container_name: cbr-ds-techtask-cpi
    environment:
    # remove before going to production
      - FLASK_ENV=development
      - PYTHONBUFFERED=True
    restart: on-failure
    volumes:
      - .:/app
    ports:
      - "5000:5000"
